name: Publish Canary Release to npmjs
on:
  release:
    types: [prereleased]

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run prerelease
      - run: npm publish --provenance --tag=canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
